#!/usr/bin/env python

import os
import sys
import os.path

# Setup Paths
PARENTDIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(PARENTDIR)

from dsbox_dev_setup import path_setup
path_setup()

import time
import grpc
import numpy
import argparse
from concurrent import futures

from dsbox.server.controller.pipeline_compute import PipelineCompute
from dsbox.server.controller.pipeline_data import PipelineData
from dsbox.server.controller.dataflow import Dataflow

numpy.set_printoptions(threshold=numpy.nan)

_ONE_DAY_IN_SECONDS = 60 * 60 * 24

DEFAULT_LIB_DIRECTORY = PARENTDIR + os.sep + "library"

def serve():
    parser = argparse.ArgumentParser()
    parser.add_argument("-l", "--library", dest="library", help="Primitives library directory. [default: %(default)s]", default=DEFAULT_LIB_DIRECTORY)
    args = parser.parse_args()

    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    library = args.library

    PipelineCompute(library).add_to_server(server)
    PipelineData().add_to_server(server)
    Dataflow().add_to_server(server)

    server.add_insecure_port('[::]:50051')
    server.start()

    try:
        while True:
            time.sleep(_ONE_DAY_IN_SECONDS)
    except KeyboardInterrupt:
        server.stop(0)

if __name__ == '__main__':
    serve()
